### ISSUE TITLE
Cannot connect to X server

### ISSUE THREAD

**Issue by Tortschi** [devicehive/devicehive-video-analysis#19]
Hello,

i get a Problem when i run the Code on an Ubuntu Server 18.04.
When i use: python eval.py –video="https://www.youtube.com/watch?v=hfeNyZV6Dsk"

i get this Error: : cannot connect to X server

Whats the Problem for it?

**Comment by Nikolay-Kha** [comment]
looks like something wants to have GUI. I don't remember any components in devicehive-video-analysis that uses actual UI... maybe opencv wants it(it has some UI components, but they are not used in this project).

Alternativly, you can try to run it with virtual UI using Xvfb.
`xvfb-run python eval.py –video="https://www.youtube.com/watch?v=hfeNyZV6Dsk"`

**Comment by Tortschi** [comment]
`[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (802) open VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
  File "eval.py", line 126, in <module>
    tf.app.run(main=evaluate)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 44, in evaluate
    raise IOError('Can\'t open "{}"'.format(FLAGS.video))
IOError: Can't open "0"
`

Now i get this Error.
