### ISSUE TITLE
Error while running python eval.py --video="https://www.youtube.com/watch?v=MKk1u5RMTn4&list=RDMMMKk1u5RMTn4"

### ISSUE THREAD

**Issue by abhaysjuneja** [devicehive/devicehive-video-analysis#3]
Traceback (most recent call last):
  File "eval.py", line 123, in <module>
    tf.flags.DEFINE_string('video', 0, 'Path to the video file.')
  File "/home/abhayjeet/.local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/home/abhayjeet/.local/lib/python2.7/site-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/abhayjeet/.local/lib/python2.7/site-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/home/abhayjeet/.local/lib/python2.7/site-packages/absl/flags/_flag.py", line 107, in __init__
    self._set_default(default)
  File "/home/abhayjeet/.local/lib/python2.7/site-packages/absl/flags/_flag.py", line 196, in _set_default
    self.default = self._parse(value)
  File "/home/abhayjeet/.local/lib/python2.7/site-packages/absl/flags/_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --video=0: flag value must be a string, found "<type 'int'>"

Installed all the requirements.
Using tensorflow-gpu 1.7.0
cuda 9.0

**Comment by abhaysjuneja** [comment]
Update: 
Uninstalled tensorflow-gpu
Install tensorflow (cpu only)

Error persists.

python daemon.py seems to work
but 127.0.0.1:8000 asks for some credentials to be saved - no clue about that.
no video stream visible @ 127.0.0.1:8000/events/
the console output shows, predicted: person since the webcam does start up and i'm sitting in front of it.

**Comment by abhaysjuneja** [comment]
Update:

Installed tensorflow 1.4.0 instead of 1.7.0

It WORKS!!  Will be testing with tensorflow-gpu==1.4.0 Let's see if that works!

Update: No it doesn't.

Required cuda toolkit 8.0 for tensorflow-gpu 1.4.0

I had cuda 9.0 installed

**Comment by abhaysjuneja** [comment]
Closed because solved.
